### ISSUE TITLE
Focus of the 'Book' page

### ISSUE THREAD

**Issue by Enegnei** [cryptoanarchywiki/cryptoanarchywiki.github.io#6]
I was about to make a pull request but wanted to ask a quick question first: is the '[Books](https://cryptoanarchy.wiki/sources/books)' page only for books read & referenced by cryptoanarchists and participants in the mailing list, or is it more generally for books written by / about cypherpunks & their interests, including recent texts?

**Comment by tombusby** [comment]
Books is for any book related to the history of cryptography or the broader cypherpunk movement.

**Comment by tombusby** [comment]
Good question though.

(Textbook typie materials I'd be more likely to include in the Primer Courses section)
